version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
    restart: always
  api:
    image: benefact-api
    depends_on:
      - db
    environment:
      ConnectionStrings:BenefactDatabase: Host=db;Username=postgres;Database=benefact;Password=verysecretpassword
    build: "api/"
  ui:
    image: benefact-ui
    environment:
      API_TARGET: api
    ports:
      - "80:80"
    build: "ui/"